version: '3.7'

x-jdbc-config: &db-config
  JDBC_URL: "jdbc:postgresql://db:5432/app"
  JDBC_DRIVER: "org.postgresql.Driver"
  JDBC_USERNAME: "postgres"
  JDBC_PASSWORD: "tour"
  JDBC_MAX_POOL: "10"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    networks:
      - server
    environment:
      <<: *db-config
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - "vdata:/var/lib/postgresql"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tour
      POSTGRES_DB: app
    restart: always
    networks:
      - server
volumes:
  vdata: {}
networks:
  server: